/home/hashcow/scripts/erase_MPOS_stratum_database.sh coin42
/home/hashcow/scripts/erase_MPOS_stratum_database.sh alpha
/home/hashcow/scripts/erase_MPOS_stratum_database.sh bbq
/home/hashcow/scripts/erase_MPOS_stratum_database.sh casino
/home/hashcow/scripts/erase_MPOS_stratum_database.sh cosmos
/home/hashcow/scripts/erase_MPOS_stratum_database.sh diamond
/home/hashcow/scripts/erase_MPOS_stratum_database.sh digibyte
/home/hashcow/scripts/erase_MPOS_stratum_database.sh digital
/home/hashcow/scripts/erase_MPOS_stratum_database.sh flappy
/home/hashcow/scripts/erase_MPOS_stratum_database.sh grand
/home/hashcow/scripts/erase_MPOS_stratum_database.sh klondike
/home/hashcow/scripts/erase_MPOS_stratum_database.sh lotto
/home/hashcow/scripts/erase_MPOS_stratum_database.sh neo
/home/hashcow/scripts/erase_MPOS_stratum_database.sh noble
/home/hashcow/scripts/erase_MPOS_stratum_database.sh redd
/home/hashcow/scripts/erase_MPOS_stratum_database.sh solar
/home/hashcow/scripts/erase_MPOS_stratum_database.sh tag
/home/hashcow/scripts/erase_MPOS_stratum_database.sh tesla
/home/hashcow/scripts/erase_MPOS_stratum_database.sh usde
/home/hashcow/scripts/erase_MPOS_stratum_database.sh world
